<%@ Page Title="" Language="C#" MasterPageFile="~/abc.master" AutoEventWireup="true" CodeFile="SubjectTool.aspx.cs" Inherits="Administrator_SubjectTool" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <telerik:RadAjaxManager ID="RadAjaxManager1" runat="server" DefaultLoadingPanelID="RadAjaxLoadingPanel1">
        <AjaxSettings>
            <telerik:AjaxSetting AjaxControlID="RBCreateSubject">
                <UpdatedControls>
                    <telerik:AjaxUpdatedControl ControlID="RBCreateSubject" UpdatePanelCssClass="" />
                    <telerik:AjaxUpdatedControl ControlID="RGSubjectGrid" UpdatePanelCssClass="" />
                    <telerik:AjaxUpdatedControl ControlID="RCBSubjectName" UpdatePanelCssClass="" />
                </UpdatedControls>
            </telerik:AjaxSetting>
            <telerik:AjaxSetting AjaxControlID="RGSubjectGrid">
                <UpdatedControls>
                    <telerik:AjaxUpdatedControl ControlID="RGSubjectGrid" UpdatePanelCssClass="" />
                    <telerik:AjaxUpdatedControl ControlID="RCBSubjectName" UpdatePanelCssClass="" />
                </UpdatedControls>
            </telerik:AjaxSetting>
            <telerik:AjaxSetting AjaxControlID="RCBSubjectName">
                <UpdatedControls>
                    <telerik:AjaxUpdatedControl ControlID="RCBSubjectName" UpdatePanelCssClass="" />
                    <telerik:AjaxUpdatedControl ControlID="RTBUpdateName" UpdatePanelCssClass="" />
                </UpdatedControls>
            </telerik:AjaxSetting>
            <telerik:AjaxSetting AjaxControlID="RBUpdate">
                <UpdatedControls>
                    <telerik:AjaxUpdatedControl ControlID="RGSubjectGrid" />
                    <telerik:AjaxUpdatedControl ControlID="RBUpdate" />
                </UpdatedControls>
            </telerik:AjaxSetting>
        </AjaxSettings>
    </telerik:RadAjaxManager>
    <telerik:RadAjaxLoadingPanel ID="RadAjaxLoadingPanel1" runat="server" Skin="Default"></telerik:RadAjaxLoadingPanel>
    <table>
        <tr>
            <td>
                <telerik:RadLabel ID="RadLabel1" runat="server" Font-Bold="true">
                    Subject Name:
                </telerik:RadLabel>
            </td>
            <td>
                <telerik:RadTextBox ID="RTBSubjectName" runat="server"></telerik:RadTextBox>
            </td>
        </tr>
    </table>

    <div align="right">
        <telerik:RadButton ID="RBCreateSubject" runat="server" Text="Go" OnClick="RBCreateSubject_Click"></telerik:RadButton>
    <telerik:RadGrid ID="RGSubjectGrid" runat="server" Height="250px" AutoGenerateColumns="False" AutoGenerateDeleteColumn="True" OnDeleteCommand="RGSubjectGrid_DeleteCommand" OnNeedDataSource="RGSubjectGrid_NeedDataSource" >
        <GroupingSettings CollapseAllTooltip="Collapse all groups"></GroupingSettings>
        <ClientSettings>
            <Scrolling AllowScroll="True" UseStaticHeaders="True" />
        </ClientSettings>
        <MasterTableView DataKeyNames="SubjectID">
            <Columns>
            
                <telerik:GridBoundColumn DataField="SubjectID" FilterControlAltText="Filter SubjectID column" HeaderText="Subject ID" UniqueName="SubjectID">
                                            <HeaderStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                                            <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
               </telerik:GridBoundColumn>
                <telerik:GridBoundColumn DataField="SubjectName" FilterControlAltText="Filter SubjectName column" HeaderText="Subject Name" UniqueName="SubjectName">
                                            <HeaderStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                                            <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
               </telerik:GridBoundColumn>
            
            </Columns>
    
        </MasterTableView>

    </telerik:RadGrid> 
        
    </div>
    <table>
        <tr>
            <td>
                <telerik:RadComboBox ID="RCBSubjectName" AutoPostBack="true" runat="server" OnSelectedIndexChanged="RCBSubjectName_SelectedIndexChanged" ></telerik:RadComboBox>
            </td>
            <td>
                <telerik:RadTextBox ID="RTBUpdateName" runat="server"></telerik:RadTextBox>
            </td>
        </tr>
    
        </table>
    <telerik:RadButton ID="RBUpdate" runat="server" Text="Modify" OnClick="RBUpdate_Click"></telerik:RadButton>
</asp:Content>

